from pathlib import Path
import json

from integration.apartment_estimator import (
    estimate_apartments
)

# ============================================================
# CONFIGURATION
# ============================================================

AVERAGE_FLOOR_HEIGHT = 3.0


# ============================================================
# LOAD BUILDINGS
# ============================================================

def load_buildings(buildings_path):
    """
    Load building polygons generated by the
    building detection pipeline.
    """

    buildings_path = Path(buildings_path)

    if not buildings_path.exists():
        raise FileNotFoundError(
            f"Building file not found: {buildings_path}"
        )

    with open(
        buildings_path,
        "r",
        encoding="utf-8"
    ) as file:

        buildings = json.load(file)

    return buildings


# ============================================================
# ESTIMATE HEIGHT
# ============================================================

def estimate_height(building):
    """
    Temporary height estimation for the prototype.

    Since real LiDAR/DSM data is not available yet,
    we use a simulated height based on building area.

    This will later be replaced by actual LiDAR/DSM
    measurements.
    """

    area = building.get(
        "area_pixels",
        0
    )

    # Temporary prototype assumption
    height = max(
        6.0,
        min(
            30.0,
            area / 100.0
        )
    )

    return round(
        height,
        2
    )


# ============================================================
# ESTIMATE FLOORS
# ============================================================

def estimate_floors(height):
    """
    Estimate number of floors from building height.
    """

    floors = round(
        height / AVERAGE_FLOOR_HEIGHT
    )

    return max(
        floors,
        1
    )


# ============================================================
# BUILD PROPERTY OBJECT
# ============================================================

def create_property(building):
    """
    Convert a detected building into a structured
    property object.
    """

    building_id = building[
        "building_id"
    ]

    area = building.get(
        "area_pixels",
        0
    )

    polygon = building.get(
        "polygon",
        []
    )

    # Temporary height
    height = estimate_height(
        building
    )

    # Estimate floors
    floors = estimate_floors(
        height
    )

    # Estimate apartments
    apartment_data = estimate_apartments(
        area,
        floors
    )

    property_data = {

        "building_id": building_id,

        "geometry": {
            "coordinate_system": "PIXEL",
            "polygon": polygon
        },

        "measurements": {

            "area_pixels": area,

            "height_meters": height,

            "estimated_floors": floors,

            "estimated_total_flats": apartment_data[
                "total_estimated_flats"
            ],

            "estimated_flats_per_floor": apartment_data[
                "estimated_flats_per_floor"
            ]
        },

        "apartments": apartment_data,

        "data_sources": {

            "building_detection": "AI",

            "height": "TEMPORARY_ESTIMATE",

            "floor_count": "ESTIMATED"
        },

        "validation": {

            "status": "NOT_VALIDATED",

            "land_record_match": False
        },

        "ulpin": None
    }

    return property_data


# ============================================================
# BUILD ALL PROPERTIES
# ============================================================

def build_property_dataset(buildings):
    """
    Convert all detected buildings into property objects.
    """

    properties = []

    for building in buildings:

        property_data = create_property(
            building
        )

        properties.append(
            property_data
        )

    return properties


# ============================================================
# SAVE PROPERTY DATA
# ============================================================

def save_properties(
    properties,
    output_path
):
    """
    Save the final property dataset.
    """

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            properties,
            file,
            indent=4
        )

    print(
        f"\nProperty data saved to:\n{output_path}"
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    # Find project root
    project_root = (
        Path(__file__)
        .resolve()
        .parent
        .parent
    )

    # Input
    buildings_path = (
        project_root
        / "outputs"
        / "buildings.json"
    )

    # Output
    output_path = (
        project_root
        / "outputs"
        / "property_data.json"
    )

    print("=" * 60)
    print("PROPERTY DATA BUILDER")
    print("=" * 60)

    try:

        # Load buildings
        print(
            "\nLoading detected buildings..."
        )

        buildings = load_buildings(
            buildings_path
        )

        print(
            "Buildings loaded:",
            len(buildings)
        )

        # Build properties
        print(
            "\nCreating property objects..."
        )

        properties = build_property_dataset(
            buildings
        )

        # Display
        for property_data in properties:

            print(
                f"\n{property_data['building_id']}"
            )

            print(
                "Area:",
                property_data[
                    "measurements"
                ][
                    "area_pixels"
                ]
            )

            print(
                "Height:",
                property_data[
                    "measurements"
                ][
                    "height_meters"
                ],
                "m"
            )

            print(
                "Estimated floors:",
                property_data[
                    "measurements"
                ][
                    "estimated_floors"
                ]
            )

            print(
                "Estimated total flats:",
                property_data[
                    "measurements"
                ][
                    "estimated_total_flats"
                ]
            )

            print(
                "Estimated flats per floor:",
                property_data[
                    "measurements"
                ][
                    "estimated_flats_per_floor"
                ]
            )

        # Save
        save_properties(
            properties,
            output_path
        )

        print(
            "\nProperty building successful!"
        )

    except Exception as error:

        print(
            "\nERROR:",
            error
        )